# Generated by Django 5.0.4 on 2024-04-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="authCredentials",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("emailid", models.CharField(max_length=300, unique=True)),
                ("password", models.CharField(max_length=500)),
                ("token", models.CharField(max_length=500, null=True)),
                (
                    "timestamp",
                    models.CharField(default=1713616762.909482, max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="createUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("account_number", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "auth",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userinfo",
                        to="User.authcredentials",
                    ),
                ),
            ],
        ),
    ]
