# Generated by Django 5.0.4 on 2024-04-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authcredentials",
            name="timestamp",
            field=models.CharField(default=1713617677.565729, max_length=50),
        ),
        migrations.AlterField(
            model_name="createuser",
            name="account_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="createuser",
            name="auth",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userinfo",
                to="User.authcredentials",
            ),
        ),
    ]
