# Generated by Django 5.0.4 on 2024-04-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_alter_authcredentials_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authcredentials",
            name="timestamp",
            field=models.CharField(default=1713857932.94532, max_length=50),
        ),
        migrations.CreateModel(
            name="userAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("account_number", models.CharField(max_length=100, null=True)),
                ("transaction", models.CharField(max_length=800)),
                (
                    "type",
                    models.CharField(
                        choices=[("Credited", "CR"), ("Debited", "DD")],
                        default="failed",
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="User.authcredentials",
                    ),
                ),
            ],
        ),
    ]
