# Generated by Django 5.0.4 on 2024-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_alter_authcredentials_timestamp_useraccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="createuser",
            name="balance",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="authcredentials",
            name="timestamp",
            field=models.CharField(default=1713872621.669033, max_length=50),
        ),
    ]
