# Generated by Django 5.0.4 on 2024-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_createuser_balance_alter_authcredentials_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authcredentials",
            name="timestamp",
            field=models.CharField(default=1713873349.26752, max_length=50),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="transaction",
            field=models.IntegerField(),
        ),
    ]
