# Generated by Django 5.0.4 on 2024-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0005_alter_authcredentials_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="transaction_id",
            field=models.CharField(default=100, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="authcredentials",
            name="timestamp",
            field=models.CharField(default=1713983136.409215, max_length=50),
        ),
        migrations.AlterField(
            model_name="createuser",
            name="mobile",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
