# Generated by Django 5.0.4 on 2024-04-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0006_useraccount_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authcredentials",
            name="timestamp",
            field=models.CharField(default=1713983207.173192, max_length=50),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="transaction_id",
            field=models.CharField(default=100, max_length=500),
        ),
    ]
